"""
Meshtastic Matrix Relay - Bridge between Meshtastic mesh networks and Matrix chat rooms.
"""

import os

try:
    # Try to get version from _version.py generated by setuptools_scm
    from ._version import version as __version__
except ImportError:
    # Get version from environment variable if available (set by GitHub Actions)
    # Otherwise, use a default version
    __version__ = os.environ.get("GITHUB_REF_NAME", "0.1.0")
