services:
  mmrelay:
    build: .
    container_name: meshtastic-matrix-relay
    restart: unless-stopped

    environment:
      - TZ=UTC
      - PYTHONUNBUFFERED=1

    volumes:
      # Mount your config.yaml file
      - ./config.yaml:/app/config.yaml:ro
      # Persistent data and logs
      - mmrelay_data:/app/data
      - mmrelay_logs:/app/logs

    # For TCP connections (most common)
    network_mode: host

    # For serial connections, uncomment the device you need:
    # devices:
    #   - /dev/ttyUSB0:/dev/ttyUSB0
    #   - /dev/ttyACM0:/dev/ttyACM0

    # For BLE connections, uncomment this:
    # privileged: true

volumes:
  mmrelay_data:
  mmrelay_logs:
