name: Build Windows Executable

permissions:
  contents: write
  issues: read

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies (non-E2EE)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executable
        run: pyinstaller --name=mmrelay.exe --onefile --console src/mmrelay/main.py

      - name: Build installer
        uses: nadeemjazmawe/inno-setup-action-cli@v6.0.5
        with:
          filepath: "/DAppVersion=${{ github.ref_name }} ./mmrelay.iss"

      - name: Upload setup.exe to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/setup.exe
          asset_name: setup.exe
          asset_content_type: application/vnd.microsoft.portable-executable
