name: Package Windows Installer

on:
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: write
  actions: read

jobs:
  build-windows-installer:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Extract version and git SHA
        id: get_version
        shell: bash
        run: |
          # Extract version from mmrelay module
          if [ -f src/mmrelay/__init__.py ]; then
            VERSION=$(python3 -c "import sys; sys.path.insert(0, 'src'); from mmrelay import __version__; print(__version__)")
          else
            VERSION="1.1.2"
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Extracted version: $VERSION"
          GIT_SHA=$(git rev-parse --short HEAD)
          echo "GIT_SHA=$GIT_SHA" >> $GITHUB_ENV
          # Set FILE_VERSION to just the version for releases, or version-dev-SHA for PRs/manual runs
          if [ "${{ github.event_name }}" == "release" ]; then
            echo "FILE_VERSION=$VERSION" >> $GITHUB_ENV
          else
            echo "FILE_VERSION=$VERSION-dev-$GIT_SHA" >> $GITHUB_ENV
          fi

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executable
        run: pyinstaller --name=mmrelay.exe --onefile --console src/mmrelay/main.py

      - name: Build installer
        uses: nadeemjazmawe/inno-setup-action-cli@v6.0.5
        with:
          filepath: "/DAppVersion=${{ env.FILE_VERSION }} ./scripts/mmrelay.iss"

      - name: Upload installer as artifact
        uses: actions/upload-artifact@v4
        with:
          name: MMRelay_setup_${{ env.FILE_VERSION }}
          path: scripts/MMRelay_setup_${{ env.FILE_VERSION }}.exe

      - name: Upload installer to GitHub Release
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: scripts/MMRelay_setup_${{ env.FILE_VERSION }}.exe
          asset_name: MMRelay_setup_${{ env.FILE_VERSION }}.exe
          tag: ${{ github.ref }}
          overwrite: true
