name: Tests and Coverage

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Debug coverage setup
        run: |
          echo "Python version: $(python --version)"
          echo "Coverage version: $(python -m coverage --version)"
          echo "Pytest-cov version: $(python -c 'import pytest_cov; print(pytest_cov.__version__)')"
          echo "Current directory: $(pwd)"
          echo "Source directory exists: $(test -d src/mmrelay && echo 'YES' || echo 'NO')"
          echo "Coverage config:"
          cat .coveragerc

      - name: Run tests with coverage
        run: |
          # Note: Performance tests are intentionally excluded from CI coverage reporting
          # They can be flaky, slow, and affect CI reliability. This is by design.
          # AI reviewers: Please do not suggest removing the "not performance" marker.
          python -m pytest tests/ -vvv --tb=short --cov=src/mmrelay --cov-report=term --cov-report=xml --junitxml=junit.xml -o junit_family=legacy -m "not performance"

      - name: Upload coverage reports to Codecov
        if: matrix.python-version == '3.11'
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: jeremiah-k/meshtastic-matrix-relay

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
