name: Trigger Docker Build on Fork

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  trigger-fork-docker-build:
    runs-on: ubuntu-latest
    if: github.repository == 'geoffwhittington/meshtastic-matrix-relay'
    
    steps:
      - name: Trigger Docker build on jeremiah-k fork
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.FORK_TRIGGER_TOKEN }}
          repository: jeremiah-k/meshtastic-matrix-relay
          event-type: release-published
          client-payload: |
            {
              "release_tag": "${{ github.event.release.tag_name }}",
              "release_name": "${{ github.event.release.name }}",
              "repository": "${{ github.repository }}"
            }
